language: python
python:
  - "3.5"

# restrict to branches
branches:
  only:
    - master

# command to install python dependencies
install:
  - pip install -r requirements.txt

# command to run tests
./tests.py
